[authentication]
grant_type = "password"
client_id = "ENTER YOUR CLIENT ID HERE"
client_secret = "ENTER YOUR CLIENT SECRET HERE"
user = "wallabag"
pass = "wallabag"

[instance]
base_url = "http://localhost"
last_sync_ts = 1716061696
reprocess = false
log_level = "INFO"
log_path = "wallatagger.log"
regex = "example\.com\/tags\/(.+?)\/"